/**
 * Writes src/data/icons.ts from the two lists that decide which reel entries
 * have a picture.
 *
 *   tools/gear-sources.json   ids downloaded by npm run icons
 *   tools/gear-local.json     ids whose file is committed here by hand
 *
 * The union is what the app is allowed to ask for. Generated rather than
 * hand-kept, because the failure mode of the two drifting apart is a 404 per
 * cell in the console — which is exactly what happened when the list said an
 * icon existed and nothing had put the file there.
 *
 *   npm run gen:icons
 */

import { readFile, writeFile } from 'node:fs/promises';

const json = async (p) => JSON.parse(await readFile(p, 'utf8'));

const sources = await json('tools/gear-sources.json');
const local = await json('tools/gear-local.json');

const ids = [...new Set([...Object.keys(sources), ...local.ids])].sort();

const header = `/**
 * Which reel entries have a picture, and where it lives.
 *
 * Every picture is a local file in public/gear/. Nothing is hotlinked, so the
 * app makes no third-party request at runtime and cannot break the day a
 * source changes its mind. Two things put files there:
 *
 *   ${Object.keys(sources).length} downloaded by \`npm run icons\` from tools/gear-sources.json
 *   ${local.ids.length} committed to the repo by hand, listed in tools/gear-local.json
 *
 * ${ids.length} of the app's 182 entries have one. The rest fall back to their name,
 * which is what every cell looked like before any of this — a designed
 * fallback, not a failure state.
 *
 * GENERATED by tools/gen-icons.mjs. Edit the two JSON files, not this.
 */

const WITH_ART = new Set([
`;

const body = ids.map((i) => `  ${JSON.stringify(i)},`).join('\n');

const footer = `
]);

/** The picture for an entry, or null if there is none. */
export function entryImageSrc(id: string | undefined | null): string | null {
  if (!id || !WITH_ART.has(id)) return null;
  return \`gear/\${id}.png\`;
}
`;

await writeFile('src/data/icons.ts', header + body + footer);
console.log(`icons.ts: ${ids.length} entries (${Object.keys(sources).length} mirrored, ${local.ids.length} committed)`);
